### ISSUE TITLE
this shouldn't be a bundle

### ISSUE THREAD

**Issue by cordoval** [mattsches/VersionEyeBundle#8]
i want to use this as a library to connect from Gush https://github.com/cordoval/gush/issues/161 and basically check that a project on the current root project directory has dependencies up to date, however in the case that these are not then I would like to create a patch.diff either if the API from VersionEye provides this or if not create it ourselves and then have Gush internally apply it into a commit and send a PR to the repo for review.

**Comment by mattsches** [comment]
Yes, use @digitalkaoz 's bundle, please :)
